# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(682, 793)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.eventList = QtWidgets.QListWidget(Form)
        self.eventList.setObjectName("eventList")
        self.verticalLayout.addWidget(self.eventList)
        self.addEventButton = QtWidgets.QPushButton(Form)
        self.addEventButton.setObjectName("addEventButton")
        self.verticalLayout.addWidget(self.addEventButton)
        self.optinsWindow = QtWidgets.QDockWidget(Form)
        self.optinsWindow.setObjectName("optinsWindow")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.changeTextButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.changeTextButton.setGeometry(QtCore.QRect(11, 154, 93, 28))
        self.changeTextButton.setObjectName("changeTextButton")
        self.removeEventButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.removeEventButton.setGeometry(QtCore.QRect(140, 154, 93, 28))
        self.removeEventButton.setObjectName("removeEventButton")
        self.completeEventButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.completeEventButton.setGeometry(QtCore.QRect(268, 154, 93, 28))
        self.completeEventButton.setObjectName("completeEventButton")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(397, 154, 60, 16))
        self.label.setObjectName("label")
        self.indexLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.indexLabel.setGeometry(QtCore.QRect(525, 154, 16, 17))
        self.indexLabel.setText("")
        self.indexLabel.setObjectName("indexLabel")
        self.decreaseFontSizeButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.decreaseFontSizeButton.setGeometry(QtCore.QRect(40, 250, 93, 28))
        self.decreaseFontSizeButton.setObjectName("decreaseFontSizeButton")
        self.increaseFontSizeButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.increaseFontSizeButton.setGeometry(QtCore.QRect(240, 250, 93, 28))
        self.increaseFontSizeButton.setObjectName("increaseFontSizeButton")
        self.fontSizeLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.fontSizeLabel.setGeometry(QtCore.QRect(150, 260, 72, 15))
        self.fontSizeLabel.setText("")
        self.fontSizeLabel.setObjectName("fontSizeLabel")
        self.optinsWindow.setWidget(self.dockWidgetContents)
        self.verticalLayout.addWidget(self.optinsWindow)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.addEventButton.clicked.connect(Form.addEvent)
        self.eventList.doubleClicked['QModelIndex'].connect(Form.openOptionsWindow)
        self.removeEventButton.clicked.connect(Form.removeEvent)
        self.changeTextButton.clicked.connect(Form.changeEventText)
        self.completeEventButton.clicked.connect(Form.completeEvent)
        self.decreaseFontSizeButton.clicked.connect(Form.decreaseEventFontSize)
        self.increaseFontSizeButton.clicked.connect(Form.increaseEventFontSize)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addEventButton.setText(_translate("Form", "添加"))
        self.changeTextButton.setText(_translate("Form", "修改文字"))
        self.removeEventButton.setText(_translate("Form", "删除"))
        self.completeEventButton.setText(_translate("Form", "完成"))
        self.label.setText(_translate("Form", "当前索引"))
        self.decreaseFontSizeButton.setText(_translate("Form", "A-"))
        self.increaseFontSizeButton.setText(_translate("Form", "A+"))
